### PR TITLE
fix(hdf5): read HDF5_BACKEND_VERSION using actual stored type(#42)

### LINKED ISSUE #42: DBEntry.get() fails after transferring IMAS HDF5 data through HSDS
Hi, thanks for developing and maintaining IMAS-Python.

## Summary
We are currently working on replacing an OMAS HDF5–based remote HSDS database with an IMAS-Python HDF5 backend in the database platform used for the VEST device.
HSDS (Highly Scalable Data Service) provides REST-based access to HDF5 data stored on distributed or cloud storage systems. Our goal is to store IMAS IDS data locally using the IMAS HDF5 backend, upload the resulting HDF5 files to an HSDS server, and later download and read them again using `imas.DBEntry.get()`.
However, after transferring the file through HSDS, reading the IDS fails with an `ImasCoreBackendException`.

## What we did
We create and store an IDS using the IMAS HDF5 backend:
```python
import imas
import os

factory = imas.IDSFactory()
pf_active = factory.pf_active()

pf_active.ids_properties.homogeneous_time = imas.ids_defs.IDS_TIME_MODE_HOMOGENEOUS
pf_active.time = [0.01]

dir_path = "/tmp/tet"
os.makedirs(dir_path, exist_ok=True)

with imas.DBEntry("imas:hdf5?path=" + dir_path, "w") as dbentry:
    dbentry.put(pf_active)
```
The file appears correct when inspected using h5py:
```python
import h5py

f = h5py.File("/tmp/tet/pf_active.h5")
print(list(f.keys()))
```
Output:
```
['pf_active']
```
Problem

When trying to read the data again:
```python
with imas.DBEntry("imas:hdf5?path=/tmp/tet", "r") as dbentry:
    ids = dbentry.get("pf_active")
```
we get the following error:
```
ImasCoreBackendException:
```
### ***Question***

Even though we upload and download the exact same file, it becomes unreadable by imas.DBEntry.get().

Is there any additional requirement (e.g., metadata, directory structure, or backend-specific information) that must be preserved when transferring IMAS HDF5 data between systems (for example through HSDS)?

### PR DESCRIPTION
**Pull request by prasad-sawantdesai**
```
$ python
Python 3.11.5 (main, Jul 30 2025, 19:17:56) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import imas
>>> with imas.DBEntry("imas:hdf5?path=./HSDS-imas/hsds", "r") as dbentry:
...     ids = dbentry.get("pf_active")
... 
13:01:49 INFO     Parsing data dictionary version 4.1.1 @dd_zip.py:89
13:01:50 INFO     Parsing data dictionary version 4.0.0 @dd_zip.py:89
>>> ids
<IDSToplevel (IDS:pf_active)>
         
>>> imas.util.print_tree(ids)
pf_active
├── ids_properties
│   ├── comment: 'testing pf_active'
│   ├── homogeneous_time: 1
│   └── ids_properties/version_put
│       ├── data_dictionary: '4.0.0'
│       ├── access_layer: '5.4.3'
│       └── access_layer_language: 'imas 2.0.0.post1'
└── time: array([0.01])
>>> with imas.DBEntry("imas:hdf5?path=./HSDS-imas/hsds", "r") as dbentry:
...     ids = dbentry.get("equilibrium")
... 
>>> ids
<IDSToplevel (IDS:equilibrium)>
>>> imas.util.print_tree(ids)
equilibrium
├── ids_properties
│   ├── comment: 'testing'
│   ├── homogeneous_time: 1
│   └── ids_properties/version_put
│       ├── data_dictionary: '4.0.0'
│       ├── access_layer: '5.4.3'
│       └── access_layer_language: 'imas 2.0.0.post1'
└── time: array([0.01])
>>> 
[3]+  Stopped                 python
[sawantp1@98dci4-srv-1003 IMAS-Core]$ 
```

### CODE REVIEW

File: src/hdf5/hdf5_utils.cpp [hunk 1]
```diff
@@ -75,24 +76,32 @@ int
...
+        H5Tclose(attr_file_type);
+
+        hid_t dtype_id = H5Tcopy(H5T_C_S1);
+        H5Tset_size(dtype_id, attr_size + 1);
+        H5Tset_strpad(dtype_id, H5T_STR_NULLTERM);
+        H5Tset_cset(dtype_id, attr_cset);
 
-        char version[10];
-        herr_t status = H5Aread(att_id, dtype_id, version);
+        std::vector<char> version(attr_size + 1, '\0');
```
Comment (paulotex) [inline src/hdf5/hdf5_utils.cpp]: Why not std::string here? std::string.c_string() gets the raw char* pointer for H5Aread... And then we don't need to include `<vector>` here...

Comment (prasad-sawantdesai) [reply src/hdf5/hdf5_utils.cpp]: Thanks, fixed here.. https://github.com/iterorganization/IMAS-Core/pull/43/commits/fa9fd35d1c9678fc30a3956296bf0fe17dde5f78

**Review by olivhoenen — APPROVED** [review]

**Comment by olivhoenen** [comment]
@fleuryl-ai are you happy with this update?

File: src/hdf5/hdf5_utils.cpp [hunk 2]
```diff
@@ -75,24 +76,30 @@ int
...
+        H5Tclose(attr_file_type);
+
+        hid_t dtype_id = H5Tcopy(H5T_C_S1);
+        H5Tset_size(dtype_id, attr_size + 1);
+        H5Tset_strpad(dtype_id, H5T_STR_NULLTERM);
 
-        char version[10];
-        herr_t status = H5Aread(att_id, dtype_id, version);
+        std::vector<char> version(attr_size + 1, '\0');
+        herr_t status = H5Aread(att_id, dtype_id, version.data());
```
Comment (fleuryl-ai) [inline src/hdf5/hdf5_utils.cpp:96]: Good job @prasad-sawantdesai!
I would increase robustness by explicitly null-terminate 'version' at the last index, adding this line:
`version[attr_size] = '\0'; `
in case it is not present when writing the version using HSDS.

**Review by fleuryl-ai — APPROVED** [review]

File: src/hdf5/hdf5_utils.cpp (hunk 2 above)
Comment (prasad-sawantdesai) [reply src/hdf5/hdf5_utils.cpp:96]: Thank you fixed here 938302002f4d49b568efbb19e3c54261c44d13ac
